name: Push to other branches

on:
  push:
    branches-ignore:
      - master
      - release/*

jobs:
  labels:
    name: Update repo labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Update labels - dry run
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Haskell Dockerfile Linter (Hadolint)
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Dockerfile

  build_and_push:
    name: Build and push images
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image and push to registry
        env:
          DOCKER_BUILDKIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color
        run: make build-parallel push-parallel VERSION_PREFIX=test-

  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create pull request - bugfix (conditional)
        if: startsWith(github.ref, 'refs/heads/bugfix')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: bugfix
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - dependency (conditional)
        if: startsWith(github.ref, 'refs/heads/dependency')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: dependency
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - documentation (conditional)
        if: startsWith(github.ref, 'refs/heads/documentation')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: documentation
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - feature (conditional)
        if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: feature
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - test (conditional)
        if: startsWith(github.ref, 'refs/heads/test')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          reviewer: ${{ github.actor }}
          label: test
          template: .github/PULL_REQUEST_TEMPLATE.md
          draft: true
          get_diff: true

      - name: Create pull request - other (conditional)
        if: "!startsWith(github.ref, 'refs/heads/bugfix') && !startsWith(github.ref, 'refs/heads/dependabot') && !startsWith(github.ref, 'refs/heads/dependency') && !startsWith(github.ref, 'refs/heads/documentation')  && !startsWith(github.ref, 'refs/heads/feature') && !startsWith(github.ref, 'refs/heads/test')"
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: feature
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true
